### ISSUE TITLE
Github action에서 mysql connection fail 뜨는 이슈

### ISSUE THREAD

**Issue by JackCokebb** [Exit-or-Die/Sitree-API#14]
github action에서 빌드 > gradle test 단계에서 에러 발생
```
Caused by:
                    com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

                    The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
                        at app//com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
                        at app//com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
                        at app//com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
                        at app//com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
                        at app//com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
                        at app//com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
                        at app//com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
                        at app//com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
                        at app//com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
                        at app//com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
                        at app//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
                        at app//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
                        at app//com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
                        at app//org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
                        at app//org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:428)
                        at app//org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:46)
                        ... 63 more
```

- gradle test 단계에서는 local profile 환경으로 돌아가는 것 같은데, mysql 설정이 localhost:3306으로 되어 있어서 mysql이 없으니 에러 발생하는 것으로 추정
- ec2에 있는 mysql에 연결하자니 local 환경의 계정 정보도 다르고 github action이 돌아가는 서버의 주소를 알 수 있는지도 몰라서 (유동적일것으로 추정) ec2 보안 설정에 추가하기도 애매함
- github action > build stage가 돌기전에 mysql 이미지를 땡겨와서 띄워줘야 할 것 같음.

**Comment by JackCokebb** [comment]
local 환경은 h2로 대체.
